version: "3.9"
networks:
  robopro:
   driver: bridge
services:
  web:
   image: web:v1
   container_name: web
   ports:
   - "80:80"
   depends_on:
   - catalouge
   - user
   - cart
   - mysql
   - shipping
  mongodb:
   image: mongodb:v1
   container_name: mongodb
  catalouge:
   image: catalouge:v1
   container_name: catalouge
   depends_on:
   - mongodb
  redis:
   image: redis
  user:
   image: user:v1
   container_name: user
   depends_on:
   - mongodb
   - redis
  cart:
   image: cart:v1
   container_name: cart
   depends_on:
   - redis
   - catalouge
  mysql:
   image: mysql:v1
   container_name: mysql
  shipping:
   image: shipping:v1
   container_name: shipping
   depends_on:
   - mysql
  rabbitmq:
   image: rabbitmq
   container_name: rabbitmq
  payment:
   image: payment:v1
   container_name: payment
   depends_on:
   - rabbitmq
  ratings:
   image: ratings:v1
   container_name: ratings
   depends_on:
   - mysql

