version: "3.9"
networks:
  robopro:
   driver: bridge
services:
  web:
   image: web:v1
   container_name: web
   ports:
   - "80:80"
   depends_on:
   - catalouge
  mongodb:
   image: mongodb:v1
   container_name: mongodb
  catalouge:
   image: catalouge:v1
   container_name: catalouge
   depends_on:
   - mongodb
  redis:
   image: redis
  user:
   image: user:v1
   container_name: user
   depends_on:
   - mongodb
   - redis
