from nginx
run rm -rf /usr/share/nginx/index.html
run rm -rf /etc/nginx/nginx.conf
run rm -rf /etc/nginx/config.d/default.conf
copy default.conf /etc/nginx/nginx.conf
add static /usr/share/nginx/html/
env CATALOUGE_HOST="catalouge"